name: Pull Request - Build

on:
  pull_request:
    branches:
      - main

env:
  JSON_PLACEHOLDER_URL: https://jsonplaceholder.typicode.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - run: pnpm install
      - run: pnpm run build
